"""add node runtime tables

Revision ID: ecea389246fd
Revises: 2c13d1f8c2f0
Create Date: 2026-05-07 20:46:53.233714+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ecea389246fd"
down_revision: Union[str, Sequence[str], None] = "2c13d1f8c2f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

node_status = postgresql.ENUM("online", "offline", name="node_status")
node_health = postgresql.ENUM(
    "unknown",
    "healthy",
    "degraded",
    "error",
    name="node_health",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    node_status.create(op.get_bind(), checkfirst=True)
    node_health.create(op.get_bind(), checkfirst=True)
    op.create_table(
        "node_activity_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("info", "warning", "error", name="node_activity_severity"),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["node.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "node_gpu_metadata",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("gpu_index", sa.Integer(), nullable=False),
        sa.Column("vendor", sa.String(length=128), nullable=True),
        sa.Column("model", sa.String(length=255), nullable=True),
        sa.Column("vram_bytes", sa.BigInteger(), nullable=True),
        sa.Column("device_name", sa.String(length=255), nullable=True),
        sa.Column("serial_number", sa.String(length=255), nullable=True),
        sa.Column("pci_bus_id", sa.String(length=128), nullable=True),
        sa.Column("metadata_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["node.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("node_id", "gpu_index"),
    )
    op.create_table(
        "node_metadata",
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("agent_version", sa.String(length=255), nullable=True),
        sa.Column("hostname", sa.String(length=255), nullable=True),
        sa.Column("os_name", sa.String(length=255), nullable=True),
        sa.Column("os_version", sa.String(length=255), nullable=True),
        sa.Column("kernel_version", sa.String(length=255), nullable=True),
        sa.Column("cpu_model", sa.String(length=255), nullable=True),
        sa.Column("cpu_architecture", sa.String(length=64), nullable=True),
        sa.Column("cpu_core_count", sa.Integer(), nullable=True),
        sa.Column("ram_bytes", sa.BigInteger(), nullable=True),
        sa.Column("metadata_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["node.id"],
        ),
        sa.PrimaryKeyConstraint("node_id"),
    )
    op.add_column(
        "node",
        sa.Column("status", node_status, nullable=False, server_default="offline"),
    )
    op.add_column(
        "node",
        sa.Column("health", node_health, nullable=False, server_default="unknown"),
    )
    op.add_column(
        "node",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )
    op.add_column(
        "node",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        ),
    )
    op.alter_column("node", "status", server_default=None)
    op.alter_column("node", "health", server_default=None)
    op.alter_column("node", "created_at", server_default=None)
    op.alter_column("node", "updated_at", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("node", "updated_at")
    op.drop_column("node", "created_at")
    op.drop_column("node", "health")
    op.drop_column("node", "status")
    op.drop_table("node_metadata")
    op.drop_table("node_gpu_metadata")
    op.drop_table("node_activity_log")
    node_health.drop(op.get_bind(), checkfirst=True)
    node_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
